"""add export jobs date params

Revision ID: 061e0df57f94
Revises: 62ead572db47
Create Date: 2026-01-29 20:26:03.113561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061e0df57f94'
down_revision: Union[str, Sequence[str], None] = '62ead572db47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('export_jobs', sa.Column('date_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'date_to')
    op.drop_column('export_jobs', 'date_from')
    # ### end Alembic commands ###
